language: python
python:
  - "3.5"
  - "3.6"
script:
  - pytest
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: diego
  password:
    secure: hjit2Zoo9HZsTEe1umQsyCb94k5gijMPqPJdMum4hAHXZL++QsKTHzflNeFXaK/Kz0urUKdEf+4wvazTYQRT1OSJ9R6huv5e91G5mI9WDlY5Ta80xHiWXhx8SZ2Jsn0KZup+Gw7lzQ1TAPPek+jSJlXwd0wZHeiSOkY6zZuzVIe5ED5g04Dkzb/CBaeHzjvwzZ9dtakqxImb9qgm76lMwiNIq2Qepahlx09bkDShAcqZlDSJCnuDrv+LPRbs9Jx3aVLt1v5c++q1e7ga7AN7OuwSeAHhTUHnxf4mOXtZ+GfBvWAioTFcbhox/ig7KwLTLpRqw3qtdnCRp8I9MdQm4rBGb1scFQZYttHZfrsOzOJmcTmAIFNmWV4RqtK6NMtIj9J7OmlS+iPDvZnN/AaSjmHjEYzgAEG6JCIIxPwM5rcsGEKdR04PsESeCb+z7UotYbZhBKOxX2HEj21nq+hlMWRH4Bjh0V0qPFc+zfdLCJVdw0h87R18ASc57+ozxgNu97/Ql3jVqf9I/Wfz2517FsAz+Tu1eIw3/lWq8QcAOnyRPOnFIoZ93A06YRtrGNgSmCiM3tVaP1MeUqTnSCibEW+mqZ6FgTB2agRmxkHD9S09YTBVp/8ZhkOekE4cgRvT7s/VdrdYFWtm3AiPW6inkNss4xCw/7p94PJkOrTJc1s=
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
