language: python
python:
  - '3.6'
script:
  - pytest
deploy:
  provider: pypi
  user: ddorn
  password:
    secure: eAlGDp1+b1qlAXGzNLx5CmZCtaMXTkUjJOJn8nPaWQ7pKYdlYncLBp7Ucl3EGIGIQ80Iobt3LSyWHIp2B3O6z/0n+8e41sAQQtdJ9YiWNju1gU0iuPUBBk5r4Eo1ld+H2GKvlEsU6NC8r6KIko77WA2JXbmGCKzUlSUKOvTzUO1YHvyeegj2/8JMUWgem8bkRTywvlQPPDIStFJNsElCq0MsznFY96oKRMTqRv5W8C0QD/4uheRPS130ZGBQeWKLbVZiCiKbyPu0XkkdlbPlI8DfJnN2wdxxbInUsLK8BE5LKSkW+mJwAhAUeA2TTSHzQBI/GF0qWQTagEog8jIdfuhCmbJ5pq0N5Vsdq+zqqHzDWiIgahOmf3/a5c+5/qICXk6KTGAzhH+uu58TYBLEuezo+3UmDTwES6dhg9N6vJG0KrzD9TzbvQt6KVjhpyH2p5yTHxYRlSsyUc1eOJ+sJRO5rEx7wnkNEyDqKl4geQp0h4yKYqpUAMfAFxBIIcHNb6VD63SKcZXQ6mU//CmRl8trUw5DSVcdFwacnWKyv4VTsjRGBNJe1RXCZPBlzlO+Q18hgUKfSDrc5k62pPJpXuMcUKwjCJYWccWCFopDixlPYRltXoXRiKiYrKZ0WHVJGgIcq5vEvadxwN4rkLBwtZVE6u4f+zfl773gPck6sTo=
  on:
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
    tags: true
